### ISSUE TITLE
Sync with the Presidio team

### ISSUE THREAD

**Issue by omri374** [insightsengineering/presidio-cli#9]
### Feature description

Hi @dinakar29 and others,

I'm Omri, one of the leads of the Microsoft Presidio project. We'd be happy to learn more about this tooling! it looks great. If you'd like to have a quick sync, please reach out to our maintainers team at presidio@microsoft.com.

Omri

**Comment by cicdguy** [comment]
Thanks for reaching out! Yes, it would be great to sync up. I'll reach out separately. Cheers!
